//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palmmedia.ReportGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Palmmedia.ReportGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added coverage information of {0}/{1} auto properties.
        /// </summary>
        internal static string AddedCoverageInformationOfProperties {
            get {
                return ResourceManager.GetString("AddedCoverageInformationOfProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added coverage information of {0}/{1} auto properties to module &apos;{2}&apos;.
        /// </summary>
        internal static string AddedCoverageInformationOfPropertiesOpenCover {
            get {
                return ResourceManager.GetString("AddedCoverageInformationOfPropertiesOpenCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added coverage information of {0}/{1} unexecuted methods.
        /// </summary>
        internal static string AddedCoverageInformationUnexecutedMethods {
            get {
                return ResourceManager.GetString("AddedCoverageInformationUnexecutedMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing {0} classes.
        /// </summary>
        internal static string AnalyzingClasses {
            get {
                return ResourceManager.GetString("AnalyzingClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemblies.
        /// </summary>
        internal static string Assemblies {
            get {
                return ResourceManager.GetString("Assemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemblies:.
        /// </summary>
        internal static string Assemblies2 {
            get {
                return ResourceManager.GetString("Assemblies2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly:.
        /// </summary>
        internal static string Assembly {
            get {
                return ResourceManager.GetString("Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By assembly.
        /// </summary>
        internal static string ByAssembly {
            get {
                return ResourceManager.GetString("ByAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By namespace, Level:.
        /// </summary>
        internal static string ByNamespace {
            get {
                return ResourceManager.GetString("ByNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class:.
        /// </summary>
        internal static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes:.
        /// </summary>
        internal static string Classes {
            get {
                return ResourceManager.GetString("Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all.
        /// </summary>
        internal static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse/Expand.
        /// </summary>
        internal static string CollapseExpand {
            get {
                return ResourceManager.GetString("CollapseExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverable.
        /// </summary>
        internal static string Coverable {
            get {
                return ResourceManager.GetString("Coverable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverable lines:.
        /// </summary>
        internal static string CoverableLines {
            get {
                return ResourceManager.GetString("CoverableLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage.
        /// </summary>
        internal static string Coverage {
            get {
                return ResourceManager.GetString("Coverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage:.
        /// </summary>
        internal static string Coverage2 {
            get {
                return ResourceManager.GetString("Coverage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage Report.
        /// </summary>
        internal static string CoverageReport {
            get {
                return ResourceManager.GetString("CoverageReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covered.
        /// </summary>
        internal static string Covered {
            get {
                return ResourceManager.GetString("Covered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covered lines:.
        /// </summary>
        internal static string CoveredLines {
            get {
                return ResourceManager.GetString("CoveredLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating report {0}/{1} (Assembly: {2}, Class: {3}).
        /// </summary>
        internal static string CreatingReport {
            get {
                return ResourceManager.GetString("CreatingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating summary.
        /// </summary>
        internal static string CreatingSummary {
            get {
                return ResourceManager.GetString("CreatingSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS &apos;{0}&apos; could not be saved: {1}.
        /// </summary>
        internal static string CssNotSaved {
            get {
                return ResourceManager.GetString("CssNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Assembly: {0}.
        /// </summary>
        internal static string CurrentAssembly {
            get {
                return ResourceManager.GetString("CurrentAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during reading file &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string ErrorDuringReadingFile {
            get {
                return ResourceManager.GetString("ErrorDuringReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during reading report &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string ErrorDuringReadingReport {
            get {
                return ResourceManager.GetString("ErrorDuringReadingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all.
        /// </summary>
        internal static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report file pattern &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string FailedReportFilePattern {
            get {
                return ResourceManager.GetString("FailedReportFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; does not exist (any more)..
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s).
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files:.
        /// </summary>
        internal static string Files2 {
            get {
                return ResourceManager.GetString("Files2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s):.
        /// </summary>
        internal static string Files3 {
            get {
                return ResourceManager.GetString("Files3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated by:.
        /// </summary>
        internal static string GeneratedBy {
            get {
                return ResourceManager.GetString("GeneratedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated on:.
        /// </summary>
        internal static string GeneratedOn {
            get {
                return ResourceManager.GetString("GeneratedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping.
        /// </summary>
        internal static string Grouping {
            get {
                return ResourceManager.GetString("Grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexing classes in directory &apos;{0}&apos;.
        /// </summary>
        internal static string IndexingClasses {
            get {
                return ResourceManager.GetString("IndexingClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiating parser for {0}.
        /// </summary>
        internal static string InitiatingParser {
            get {
                return ResourceManager.GetString("InitiatingParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter &apos;{0}&apos; is invalid. Filters must start with &apos;+&apos; or &apos;-&apos;..
        /// </summary>
        internal static string InvalidFilter {
            get {
                return ResourceManager.GetString("InvalidFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading report &apos;{0}&apos;.
        /// </summary>
        internal static string LoadingReport {
            get {
                return ResourceManager.GetString("LoadingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrics.
        /// </summary>
        internal static string Metrics {
            get {
                return ResourceManager.GetString("Metrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No assemblies have been covered..
        /// </summary>
        internal static string NoAssembliesHaveBeenCovered {
            get {
                return ResourceManager.GetString("NoAssembliesHaveBeenCovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files found. This usually happens if a file isn&apos;t covered by a test or the class does not contain any sequence points (e.g. a class that only contains auto properties)..
        /// </summary>
        internal static string NoFilesFound {
            get {
                return ResourceManager.GetString("NoFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No grouping.
        /// </summary>
        internal static string NoGrouping {
            get {
                return ResourceManager.GetString("NoGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No report files specified..
        /// </summary>
        internal static string NoReportFiles {
            get {
                return ResourceManager.GetString("NoReportFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No target directory specified..
        /// </summary>
        internal static string NoTargetDirectory {
            get {
                return ResourceManager.GetString("NoTargetDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report file &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string NotExistingReportFile {
            get {
                return ResourceManager.GetString("NotExistingReportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser:.
        /// </summary>
        internal static string Parser {
            get {
                return ResourceManager.GetString("Parser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preprocessing report.
        /// </summary>
        internal static string PreprocessingReport {
            get {
                return ResourceManager.GetString("PreprocessingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report generation took {0} seconds.
        /// </summary>
        internal static string ReportGenerationTook {
            get {
                return ResourceManager.GetString("ReportGenerationTook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report &apos;{0}&apos; could not be saved: {1}.
        /// </summary>
        internal static string ReportNotSaved {
            get {
                return ResourceManager.GetString("ReportNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable filtering.
        /// </summary>
        internal static string ShowCustomizeBox {
            get {
                return ResourceManager.GetString("ShowCustomizeBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This may take some time since the report contains many classes..
        /// </summary>
        internal static string ShowCustomizeBoxHelp {
            get {
                return ResourceManager.GetString("ShowCustomizeBoxHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source code directory &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string SourceDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("SourceDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target directory &apos;{0}&apos; could not be created: {1}.
        /// </summary>
        internal static string TargetDirectoryCouldNotBeCreated {
            get {
                return ResourceManager.GetString("TargetDirectoryCouldNotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test methods.
        /// </summary>
        internal static string Testmethods {
            get {
                return ResourceManager.GetString("Testmethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total lines:.
        /// </summary>
        internal static string TotalLines {
            get {
                return ResourceManager.GetString("TotalLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncovered.
        /// </summary>
        internal static string Uncovered {
            get {
                return ResourceManager.GetString("Uncovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncovered lines:.
        /// </summary>
        internal static string UncoveredLines {
            get {
                return ResourceManager.GetString("UncoveredLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown report type..
        /// </summary>
        internal static string UnknownReportType {
            get {
                return ResourceManager.GetString("UnknownReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown verbosity level..
        /// </summary>
        internal static string UnknownVerbosityLevel {
            get {
                return ResourceManager.GetString("UnknownVerbosityLevel", resourceCulture);
            }
        }
    }
}
